# Postgresql database for production, development and testing.

development:
  adapter: postgresql
  encoding: unicode
  database: sigma_nu_dev
  pool: 5
  timeout: 5000
  username: sigma_nu 
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: sigma_nu_test
  pool: 5
  timeout: 5000
  username: sigma_nu
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: sigma_nu_prod
  pool: 5
  timeout: 5000
  username: sigma_nu
  password: